import {
  FaBookReader,
  FaShoppingCart,
  FaLaptop,
  FaCar,
  FaMobileAlt,
  FaTshirt,
  FaPencilAlt,
  FaCamera,
  FaHeadphones,
  FaApple,
  FaBriefcaseMedical,
  FaBlender,
  FaCouch,
  FaUmbrellaBeach,
  FaToolbox,
  FaTv,
  FaBed,
  FaDrumstickBite,
  FaPrescriptionBottleAlt,
  FaBicycle,
  FaWineGlassAlt,
} from "react-icons/fa";
import {
  IoReaderSharp,
  IoShirt,
  IoFootstepsSharp,
  IoTabletPortrait,
  IoSchool,
  IoFastFood,
} from "react-icons/io5";
import { LuFileSpreadsheet } from "react-icons/lu";
import {
  GiSofa,
  GiElectric,
  GiCoffeeCup,
  GiGuitar,
  GiCampingTent,
} from "react-icons/gi";
import {
  MdOutlineSportsSoccer,
  MdOutlineSportsTennis,
  MdPets,
  MdOutlinePhonelink,
} from "react-icons/md";
import { BsPhone, BsWatch } from "react-icons/bs";
import { AiFillGift } from "react-icons/ai";

export const icons = [
  { id: 1, name: "BookReader", icon: <FaBookReader />, isSelected: true },
  { id: 2, name: "ReaderSharp", icon: <IoReaderSharp />, isSelected: false },
  { id: 3, name: "FileSpreadsheet", icon: <LuFileSpreadsheet />, isSelected: false },
  { id: 4, name: "ShoppingCart", icon: <FaShoppingCart />, isSelected: false },
  { id: 5, name: "Laptop", icon: <FaLaptop />, isSelected: false },
  { id: 6, name: "MobileAlt", icon: <FaMobileAlt />, isSelected: false },
  { id: 7, name: "TabletPortrait", icon: <IoTabletPortrait />, isSelected: false },
  { id: 8, name: "Car", icon: <FaCar />, isSelected: false },
  { id: 9, name: "Tshirt", icon: <FaTshirt />, isSelected: false },
  { id: 10, name: "Shirt", icon: <IoShirt />, isSelected: false },
  { id: 11, name: "PencilAlt", icon: <FaPencilAlt />, isSelected: false },
  { id: 12, name: "Camera", icon: <FaCamera />, isSelected: false },
  { id: 13, name: "Headphones", icon: <FaHeadphones />, isSelected: false },
  { id: 14, name: "Apple", icon: <FaApple />, isSelected: false },
  { id: 15, name: "BriefcaseMedical", icon: <FaBriefcaseMedical />, isSelected: false },
  { id: 16, name: "Blender", icon: <FaBlender />, isSelected: false },
  { id: 17, name: "Sofa", icon: <GiSofa />, isSelected: false },
  { id: 18, name: "Couch", icon: <FaCouch />, isSelected: false },
  { id: 19, name: "UmbrellaBeach", icon: <FaUmbrellaBeach />, isSelected: false },
  { id: 20, name: "FootstepsSharp", icon: <IoFootstepsSharp />, isSelected: false },
  { id: 21, name: "Toolbox", icon: <FaToolbox />, isSelected: false },
  { id: 22, name: "Electric", icon: <GiElectric />, isSelected: false },
  { id: 23, name: "Tv", icon: <FaTv />, isSelected: false },
  { id: 24, name: "SportsSoccer", icon: <MdOutlineSportsSoccer />, isSelected: false },
  { id: 25, name: "SportsTennis", icon: <MdOutlineSportsTennis />, isSelected: false },
  { id: 26, name: "Bed", icon: <FaBed />, isSelected: false },
  { id: 27, name: "DrumstickBite", icon: <FaDrumstickBite />, isSelected: false },
  { id: 28, name: "CoffeeCup", icon: <GiCoffeeCup />, isSelected: false },
  { id: 29, name: "Guitar", icon: <GiGuitar />, isSelected: false },
  { id: 30, name: "Pets", icon: <MdPets />, isSelected: false },
  { id: 31, name: "School", icon: <IoSchool />, isSelected: false },
  { id: 32, name: "Phonelink", icon: <MdOutlinePhonelink />, isSelected: false },
  { id: 33, name: "PrescriptionBottleAlt", icon: <FaPrescriptionBottleAlt />, isSelected: false },
  { id: 34, name: "Bicycle", icon: <FaBicycle />, isSelected: false },
  { id: 35, name: "WineGlassAlt", icon: <FaWineGlassAlt />, isSelected: false },
  { id: 36, name: "FastFood", icon: <IoFastFood />, isSelected: false },
  { id: 37, name: "Phone", icon: <BsPhone />, isSelected: false },
  { id: 38, name: "Watch", icon: <BsWatch />, isSelected: false },
  { id: 39, name: "Gift", icon: <AiFillGift />, isSelected: false },
  { id: 40, name: "CampingTent", icon: <GiCampingTent />, isSelected: false },
];